services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "budget_tracker"
    ports:
      - "5432:5432"
    volumes:
      - bt_db:/var/lib/postgresql/data
      - ./bt-server/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bt_network

  backend:
    build: ./bt-server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/budget_tracker
    ports:
      - "4000:4000"
    networks:
      - bt_network

  frontend:
    build: ./bt-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bt_network

volumes:
  bt_db:

networks:
  bt_network:
